[package]
name = "ubachain"
version = "0.1.0"
edition = "2024"
resolver = "1"

[dependencies]
clap = { workspace = true }
node = { path = "../node" }
thiserror = { workspace = true }
tokio = { workspace = true }

